# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VROOM_for_QGIS
                                 A QGIS plugin
 This plugin makes it possible to send data from a QGIS layer to VROOM.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-21
        copyright            : (C) 2025 by Suddber
        email                : suddb@posteo.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Suddber'
__date__ = '2025-04-21'
__copyright__ = '(C) 2025 by Suddber'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VROOM_for_QGIS class from file VROOM_for_QGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vroom_for_qgis import VROOM_for_QGISPlugin
    return VROOM_for_QGISPlugin()
